name: create-profiles
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: rake
        run: bundle exec rake
      - name: archive
        uses: actions/upload-artifact@v2
        with:
          name: profiles
          path: Hiking_SAC2-SHRP.brf